services:
  postgres:
    image: postgres:latest
    container_name: grumpy-senior-postgres
    environment:
      POSTGRES_DB: grumpy-senior
      POSTGRES_USER: grumpy
      POSTGRES_PASSWORD: very123grumpy!
    labels:
      - "org.springframework.boot.service-connection=postgres"
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  ollama:
    image: 'ollama/ollama:latest'
    ports:
      - "11434:11434"
    volumes:
      - ollama-models:/root/.ollama

volumes:
  postgres-data:
  ollama-models: