spring.application.name=grumpy-senior

# Auth props
jwt.public.key=classpath:certs/public.pem
jwt.private.key=classpath:certs/private-pkcs8.pem

# Database props
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:db/schema.sql,classpath:db/data.sql
